{
 "title": "Fraud Dashboard Demo DSC",
 "time": { "from": "2023-05-19T07:06:02.353Z", "to": "2023-05-19T07:10:53.675Z" },
 "panels": [
  {
   "title": "Total Request",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Non-Fraud",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum_non_fraud", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Fraud",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum_fraud", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Fraud Probability",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "probability_fraud{instance=\"fraud-detection-api-app-1:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}